language: java

# Skip the default install step
install: true

# Only run checkstyle and build the example projects in JDK8
script:
  - jdk_switcher use oraclejdk8
  - ./gradlew assemble
  - ./gradlew check
  - jdk_switcher use oraclejdk7
  - ./gradlew clean
  - ./gradlew :assemble
  - ./gradlew :test
  - jdk_switcher use openjdk7
  - ./gradlew clean
  - ./gradlew :assemble
  - ./gradlew :test
  - jdk_switcher use openjdk6
  - ./gradlew clean
  - ./gradlew :assemble
  - ./gradlew :test
