language: java

notifications:
  hipchat:
    secure: "IuIpGONbP1fsa3Gp9YplQZJqGO9fhqXSNzKYku3d6dHBVJKJ5Xnx71f4BDNQ7uD9QqBnzOoFjQtP1wju3EXA2VhBm/QIIN622NeUrZxOA/QkGNsScJ0gpjmz9awbMh2B/RikAHBt8o44wxnxnyTK8COc+CjRmEoA1ZwEtJW3Pyw="