sudo: required
language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
install: ./gradlew :bugsnag:assemble :bugsnag-spring:assemble
addons:
  apt:
    packages:
      - openjdk-6-jdk

jobs:
  include:
  - stage: test
    jdk: openjdk6
    before_install:
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    script: # Exclude examples from JDK7 build as they are written for JDK8
      - for dir in examples/*/; do echo "-x examples:`basename $dir`:test"; done | xargs ./gradlew test
  # - stage: test
  #   jdk: openjdk8
  #   script:
  #     - ./gradlew check test
  # - stage: test
  #   jdk: oraclejdk9
  #   script:
  #     - ./gradlew check test
  # - stage: test
  #   jdk: oraclejdk8
  #   script:
  #     - ./gradlew check test
  # - stage: test
  #   jdk: openjdk7
  #   script: # Exclude examples from JDK7 build as they are written for JDK8
  #     - for dir in examples/*/; do echo "-x examples:`basename $dir`:test"; done | xargs ./gradlew test
  #   before_install: # Work around missing crypto in openjdk7
  #   - sudo wget "https://bouncycastle.org/download/bcprov-ext-jdk15on-158.jar" -O "${JAVA_HOME}/jre/lib/ext/bcprov-ext-jdk15on-158.jar"
  #   - sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security
  #   - echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/java-7-openjdk/security/java.security
  # - stage: test
  #   name: mazerunner
  #   jdk: openjdk8
  #   script:
  #     - bundle install
  #     - bundle exec bugsnag-maze-runner
